package main

import (
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/zaker/jsonclient"
)

type AutoGenerated struct {
	TokenEndpoint                     string   `json:"token_endpoint"`
	TokenEndpointAuthMethodsSupported []string `json:"token_endpoint_auth_methods_supported"`
	JwksURI                           string   `json:"jwks_uri"`
	ResponseModesSupported            []string `json:"response_modes_supported"`
	SubjectTypesSupported             []string `json:"subject_types_supported"`
	IDTokenSigningAlgValuesSupported  []string `json:"id_token_signing_alg_values_supported"`
	ResponseTypesSupported            []string `json:"response_types_supported"`
	ScopesSupported                   []string `json:"scopes_supported"`
	Issuer                            string   `json:"issuer"`
	MicrosoftMultiRefreshToken        bool     `json:"microsoft_multi_refresh_token"`
	AuthorizationEndpoint             string   `json:"authorization_endpoint"`
	DeviceAuthorizationEndpoint       string   `json:"device_authorization_endpoint"`
	HTTPLogoutSupported               bool     `json:"http_logout_supported"`
	FrontchannelLogoutSupported       bool     `json:"frontchannel_logout_supported"`
	EndSessionEndpoint                string   `json:"end_session_endpoint"`
	ClaimsSupported                   []string `json:"claims_supported"`
	CheckSessionIframe                string   `json:"check_session_iframe"`
	UserinfoEndpoint                  string   `json:"userinfo_endpoint"`
	KerberosEndpoint                  string   `json:"kerberos_endpoint"`
	TenantRegionScope                 string   `json:"tenant_region_scope"`
	CloudInstanceName                 string   `json:"cloud_instance_name"`
	CloudGraphHostName                string   `json:"cloud_graph_host_name"`
	MsgraphHost                       string   `json:"msgraph_host"`
	RbacURL                           string   `json:"rbac_url"`
}

func (ag AutoGenerated) String() string {
	sb := &strings.Builder{}
	sb.WriteString(ag.TokenEndpoint)

	return sb.String()
}

func main() {
	c, err := jsonclient.NewClient[AutoGenerated]("https://login.microsoftonline.com", jsonclient.WithClient[AutoGenerated](&http.Client{}))
	if err != nil {
		log.Fatal(err)
	}
	returnObject, err := c.GET("/d8df8faf-155b-4c42-a012-350dcc1f9972/.well-known/openid-configuration")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(returnObject)
}
